/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/MDIApplication.java to edit this template
 */
package Admin;

/**
 *
 * @author cliente
 */
public class frmGestionarUsuario extends javax.swing.JFrame {

    /**
     * Creates new form frmGestionarUsuario
     */
    public frmGestionarUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        desktopPane = new javax.swing.JDesktopPane();
        tlbFiaSupport = new javax.swing.JToolBar();
        lblFiaSupport = new javax.swing.JLabel();
        lblLogo = new javax.swing.JLabel();
        btnNuevoUsuario = new javax.swing.JButton();
        btnActualizarUsuario = new javax.swing.JButton();
        btnBuscarUsuario = new javax.swing.JButton();
        btnEliminarUsuario = new javax.swing.JButton();
        btnVolverInicio = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        desktopPane.setBackground(new java.awt.Color(204, 204, 204));
        desktopPane.setForeground(new java.awt.Color(153, 153, 153));

        tlbFiaSupport.setBackground(new java.awt.Color(153, 153, 153));
        tlbFiaSupport.setRollover(true);

        lblFiaSupport.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        lblFiaSupport.setForeground(new java.awt.Color(0, 0, 0));
        lblFiaSupport.setText("FIA Support");
        tlbFiaSupport.add(lblFiaSupport);

        desktopPane.add(tlbFiaSupport);
        tlbFiaSupport.setBounds(0, 0, 440, 110);

        lblLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Fia_Support_Logo-convertido-a-100x100 (2).png"))); // NOI18N
        desktopPane.add(lblLogo);
        lblLogo.setBounds(450, 10, 100, 100);

        btnNuevoUsuario.setBackground(new java.awt.Color(102, 102, 102));
        btnNuevoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnNuevoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/agregar usuario.png"))); // NOI18N
        btnNuevoUsuario.setText("Nuevo usuario");
        desktopPane.add(btnNuevoUsuario);
        btnNuevoUsuario.setBounds(200, 160, 170, 40);

        btnActualizarUsuario.setBackground(new java.awt.Color(102, 102, 102));
        btnActualizarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnActualizarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/actualizar usuario.png"))); // NOI18N
        btnActualizarUsuario.setText("Actualizar usuario");
        desktopPane.add(btnActualizarUsuario);
        btnActualizarUsuario.setBounds(200, 230, 170, 42);

        btnBuscarUsuario.setBackground(new java.awt.Color(102, 102, 102));
        btnBuscarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnBuscarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/buscar usuario.png"))); // NOI18N
        btnBuscarUsuario.setText("Buscar usuario");
        desktopPane.add(btnBuscarUsuario);
        btnBuscarUsuario.setBounds(200, 310, 170, 42);

        btnEliminarUsuario.setBackground(new java.awt.Color(102, 102, 102));
        btnEliminarUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnEliminarUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/eliminar usuario.png"))); // NOI18N
        btnEliminarUsuario.setText("Eliminar usuario");
        desktopPane.add(btnEliminarUsuario);
        btnEliminarUsuario.setBounds(200, 390, 170, 42);

        btnVolverInicio.setBackground(new java.awt.Color(102, 102, 102));
        btnVolverInicio.setForeground(new java.awt.Color(255, 255, 255));
        btnVolverInicio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/volver inicio.png"))); // NOI18N
        btnVolverInicio.setText("Volver a inicio");
        desktopPane.add(btnVolverInicio);
        btnVolverInicio.setBounds(200, 470, 170, 40);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 564, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(desktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 541, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    /*public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
      /*  try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmGestionarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmGestionarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmGestionarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmGestionarUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
       /* java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmGestionarUsuario().setVisible(true);
            }
      //  });
    //}*/

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarUsuario;
    private javax.swing.JButton btnBuscarUsuario;
    private javax.swing.JButton btnEliminarUsuario;
    private javax.swing.JButton btnNuevoUsuario;
    private javax.swing.JButton btnVolverInicio;
    private javax.swing.JDesktopPane desktopPane;
    private javax.swing.JLabel lblFiaSupport;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JToolBar tlbFiaSupport;
    // End of variables declaration//GEN-END:variables

}
