/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vista.Login;

import Vista.Admin.GestionUsuariosUI;
import controlador.LoginController;
import controlador.ReportingController;
import controlador.TicketController;
import controlador.UserAdminController;
import java.awt.Image;
import java.net.URL;
import java.util.Arrays;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import modelo.repo.AdminRepository;
import modelo.repo.CarreraRepository;
import modelo.repo.EstadisticasAdminRepository;
import modelo.repo.EstadisticasUsuarioRepository;
import modelo.repo.FacultadRepository;
import modelo.repo.TicketRepository;
import modelo.repo.UsuarioRepository;
import modelo.servicios.AuthService;
import modelo.servicios.ReportingService;
import modelo.servicios.TicketService;
import modelo.servicios.UserAdminService;
import modelo.servicios.UsuarioService;
import modelo.servicios.WorkflowService;
import com.mycompany.soporte.SoporteFrame;

/**
 *
 * @author Méndez
 */
public class LoginUI extends javax.swing.JFrame {

    private LoginController controller;

    /**
     * Creates new form LoginUI
     */
    public LoginUI() {
        initComponents();
        setLocationRelativeTo(null);
        setResizable(false);
        setTitle("FIA Support");
        ImageIcon frameIcon = loadIcon("/Vista/img/icon.png");
        if (frameIcon != null) {
            setIconImage(frameIcon.getImage());
        }
    }

    private ImageIcon loadIcon(String resourcePath) {
        URL resource = getClass().getResource(resourcePath);
        if (resource == null) {
            System.err.println("No se pudo encontrar el recurso de imagen: " + resourcePath);
            return null;
        }
        return new ImageIcon(resource);
    }

    public void setController(LoginController controller) {
        this.controller = controller;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelMain = new javax.swing.JPanel();
        jPanelTop = new javax.swing.JPanel();
        jLabelBienvenido = new javax.swing.JLabel();
        jLabelLogo = new javax.swing.JLabel();
        jPanelLogin = new javax.swing.JPanel();
        jLabelTitulo = new javax.swing.JLabel();
        jLabelCarnet = new javax.swing.JLabel();
        txtCarnet = new javax.swing.JTextField();
        jLabelPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        btnIniciar = new javax.swing.JButton();
        jLabelProblemas = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanelMain.setBackground(new java.awt.Color(255, 255, 255));

        jPanelTop.setBackground(new java.awt.Color(180, 40, 25));

        jLabelBienvenido.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabelBienvenido.setForeground(new java.awt.Color(255, 255, 255));
        jLabelBienvenido.setText("¡Bienvenido!");

        javax.swing.GroupLayout jPanelTopLayout = new javax.swing.GroupLayout(jPanelTop);
        jPanelTop.setLayout(jPanelTopLayout);
        jPanelTopLayout.setHorizontalGroup(
                jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelTopLayout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jLabelBienvenido)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanelTopLayout.setVerticalGroup(
                jPanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelTopLayout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabelBienvenido)
                                .addContainerGap(10, Short.MAX_VALUE))
        );

        // Load image icon from package
        jLabelLogo.setSize(582, 844);
        jLabelLogo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelLogo.setVerticalAlignment(javax.swing.SwingConstants.CENTER);
        URL logoResource = getClass().getResource("/Vista/img/Logo.png");
        if (logoResource != null) {
            ImageIcon originalIcon = new ImageIcon(logoResource);
            Image scaledImage = originalIcon.getImage().getScaledInstance(160, -1, Image.SCALE_SMOOTH);
            jLabelLogo.setIcon(new ImageIcon(scaledImage));
        } else {
            System.err.println("No se pudo cargar el logo desde /Vista/img/Logo.png");
            jLabelLogo.setText("Logo no disponible");
        }

        jPanelLogin.setBackground(new java.awt.Color(180, 40, 25));

        jLabelTitulo.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabelTitulo.setForeground(new java.awt.Color(255, 255, 255));
        jLabelTitulo.setText("Ingresa tu usuario");

        jLabelCarnet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelCarnet.setForeground(new java.awt.Color(255, 255, 255));
        jLabelCarnet.setText("Carnet");

        txtCarnet.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtCarnet.setToolTipText("Digite su carnet. Ejemplo: NZ03021");

        jLabelPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabelPassword.setForeground(new java.awt.Color(255, 255, 255));
        jLabelPassword.setText("Contraseña");

        txtPassword.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnIniciar.setBackground(new java.awt.Color(204, 0, 0));
        btnIniciar.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        btnIniciar.setForeground(new java.awt.Color(255, 255, 255));
        btnIniciar.setText("Iniciar Sesión");
        btnIniciar.setFocusPainted(false);
        btnIniciar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelLoginLayout = new javax.swing.GroupLayout(jPanelLogin);
        jPanelLogin.setLayout(jPanelLoginLayout);
        jPanelLoginLayout.setHorizontalGroup(
                jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelLoginLayout.createSequentialGroup()
                                .addGap(40, 40, 40)
                                .addGroup(jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabelTitulo)
                                        .addComponent(jLabelCarnet)
                                        .addComponent(txtCarnet)
                                        .addComponent(jLabelPassword)
                                        .addComponent(txtPassword)
                                        .addComponent(btnIniciar, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE))
                                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanelLoginLayout.setVerticalGroup(
                jPanelLoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelLoginLayout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addComponent(jLabelTitulo)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelCarnet)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(15, 15, 15)
                                .addComponent(jLabelPassword)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnIniciar, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(20, Short.MAX_VALUE))
        );

        jLabelProblemas.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabelProblemas.setForeground(new java.awt.Color(180, 40, 25));
        jLabelProblemas.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelProblemas.setText("¿Problemas con el carnet o la contraseña?");
        jLabelProblemas.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));

        javax.swing.GroupLayout jPanelMainLayout = new javax.swing.GroupLayout(jPanelMain);
        jPanelMain.setLayout(jPanelMainLayout);
        jPanelMainLayout.setHorizontalGroup(
                jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanelMainLayout.createSequentialGroup()
                                .addContainerGap(275, Short.MAX_VALUE)
                                .addGroup(jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                                                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(410, 410, 410))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                                                .addComponent(jPanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(275, 275, 275))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelMainLayout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelProblemas, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(330, 330, 330))
        );
        jPanelMainLayout.setVerticalGroup(
                jPanelMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelMainLayout.createSequentialGroup()
                                .addComponent(jPanelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(50, 50, 50)
                                .addComponent(jLabelLogo, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(40, 40, 40)
                                .addComponent(jPanelLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelProblemas)
                                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();

        btnIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIniciarActionPerformed(evt);
            }
        });
        jLabelProblemas.addMouseListener(new java.awt.event.MouseAdapter() {
            @Override
            public void mouseClicked(java.awt.event.MouseEvent e) {
                new ForgotDialog(LoginUI.this).setVisible(true);
            }

            @Override
            public void mouseEntered(java.awt.event.MouseEvent e) {
                jLabelProblemas.setText("<html><u>¿Problemas con el carnet o la contraseña?</u></html>");
            }

            @Override
            public void mouseExited(java.awt.event.MouseEvent e) {
                jLabelProblemas.setText("¿Problemas con el carnet o la contraseña?");
            }
        });

    }

    private void btnIniciarActionPerformed(java.awt.event.ActionEvent evt) {
        // Placeholders opcionales (por si los usas)
        final String PLACEHOLDER_CARNET = "Ingrese su carnet";
        final String PLACEHOLDER_PASS = "Ingrese su contraseña";

        // Obtiene los textos
        String carnet = txtCarnet.getText().trim();
        String pass = new String(txtPassword.getPassword());

        // Trata placeholders como vacío
        boolean carnetVacio = carnet.isEmpty() || PLACEHOLDER_CARNET.equals(carnet);
        boolean passVacia = pass.isEmpty() || PLACEHOLDER_PASS.equals(pass);

        // Validaciones mínimas
        if (carnetVacio) {
            txtCarnet.requestFocus();
            txtCarnet.setToolTipText("Ingrese su carnet.");
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Ingrese su carnet.",
                    "Validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (passVacia) {
            txtPassword.requestFocus();
            txtPassword.setToolTipText("Ingrese su contraseña.");
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Ingrese su contraseña.",
                    "Validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        // Valida formato del carnet (solo letras/números)
        if (!carnet.matches("^[A-Za-z0-9]+$")) {
            txtCarnet.requestFocus();
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Carnet inválido (solo letras o números).",
                    "Validación",
                    javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (controller == null) {
            JOptionPane.showMessageDialog(this,
                    "No hay controlador configurado para el login.",
                    "FIA Support",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }

        char[] password = pass.toCharArray();
        try {
            controller.handleLogin(carnet, password);
        } catch (IllegalArgumentException | IllegalStateException ex) {
            JOptionPane.showMessageDialog(this,
                    ex.getMessage(),
                    "FIA Support",
                    JOptionPane.ERROR_MESSAGE);
        } finally {
            Arrays.fill(password, '\0');
            txtPassword.setText("");
        }
    }

    // </editor-fold>//GEN-END:initComponents
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            UsuarioRepository usuarioRepository = new UsuarioRepository();
            AdminRepository adminRepository = new AdminRepository();
            AuthService authService = new AuthService(usuarioRepository, adminRepository);

            TicketRepository ticketRepository = new TicketRepository();
            TicketService ticketService = new TicketService(ticketRepository, usuarioRepository);
            TicketController ticketController = new TicketController(ticketService);
            WorkflowService workflowService = new WorkflowService(ticketRepository);

            ReportingService reportingService = new ReportingService(
                    new EstadisticasAdminRepository(),
                    new EstadisticasUsuarioRepository());
            ReportingController reportingController = new ReportingController(reportingService);

            FacultadRepository facultadRepository = new FacultadRepository();
            CarreraRepository carreraRepository = new CarreraRepository();
            UsuarioService usuarioService = new UsuarioService(usuarioRepository, facultadRepository, carreraRepository);
            UserAdminService userAdminService = new UserAdminService(usuarioService);
            GestionUsuariosUI adminView = new GestionUsuariosUI();
            adminView.setReportingController(reportingController);
            UserAdminController userAdminController = new UserAdminController(userAdminService, adminView);

            LoginUI loginUI = new LoginUI();
            LoginController loginController = new LoginController(
                    authService,
                    loginUI,
                    ticketController,
                    workflowService,
                    SoporteFrame::new,
                    userAdminController,
                    adminView,
                    reportingController
            );
            loginController.showLogin();
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnIniciar;
    private javax.swing.JLabel jLabelBienvenido;
    private javax.swing.JLabel jLabelCarnet;
    private javax.swing.JLabel jLabelLogo;
    private javax.swing.JLabel jLabelPassword;
    private javax.swing.JLabel jLabelProblemas;
    private javax.swing.JLabel jLabelTitulo;
    private javax.swing.JPanel jPanelLogin;
    private javax.swing.JPanel jPanelMain;
    private javax.swing.JPanel jPanelTop;
    private javax.swing.JTextField txtCarnet;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
