/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package ui;

import com.tuapp.seguridad.captcha.CaptchaPanel;
import com.tuapp.seguridad.captcha.CaptchaProvider;
import com.tuapp.seguridad.captcha.CaptchaVerifier;
import com.tuapp.seguridad.captcha.LocalCaptchaProvider;

/**
 *
 * @author ceol7
 */
public class ProblemasCarnetContrasenaDialog extends javax.swing.JDialog {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ProblemasCarnetContrasenaDialog.class.getName());

    private CaptchaPanel captchaPanel;

    /**
     * Creates new form ProblemasCarnetContrasenaDialog
     */
    public ProblemasCarnetContrasenaDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();

        final String ICON = "/img/Fia_Support_Icon.png"; // tu archivo nuevo

// Escalar el icono del label a 50 px de alto (manteniendo proporción)
        javax.swing.Icon raw = lblIcono.getIcon();
        if (raw instanceof javax.swing.ImageIcon) {
            javax.swing.ImageIcon imgIcon = (javax.swing.ImageIcon) raw;
            java.awt.Image img = imgIcon.getImage();
            int w = img.getWidth(null), h = img.getHeight(null);
            if (w > 0 && h > 0) {
                int maxH = 50, maxW = 50;
                double s = Math.min((double) maxW / w, (double) maxH / h);
                int nw = Math.max(1, (int) Math.round(w * s));
                int nh = Math.max(1, (int) Math.round(h * s));
                java.awt.Image scaled = img.getScaledInstance(nw, nh, java.awt.Image.SCALE_SMOOTH);
                lblIcono.setIcon(new javax.swing.ImageIcon(scaled));
                lblIcono.setPreferredSize(new java.awt.Dimension(nw, nh)); // opcional
            }
        }

        // Placeholders
        addPlaceholder(txtCorreoPersonal, "Digite su correo electrónico personal");
        addPlaceholder(txtCarnet, "Digite su carnet");

        // Enter = Enviar
        getRootPane().setDefaultButton(btnEnviar);

        // Esc = cerrar
        getRootPane().registerKeyboardAction(
                e -> dispose(),
                javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_ESCAPE, 0),
                javax.swing.JComponent.WHEN_IN_FOCUSED_WINDOW
        );

        // Centrar sobre la ventana padre
        setLocationRelativeTo(parent);
        
        // --- CAPTCHA: provider + verifier + panel visual ---
CaptchaProvider provider = new LocalCaptchaProvider(); // hoy OFFLINE; luego puedes cambiar a Remote
CaptchaVerifier verifier = new CaptchaVerifier(provider);
captchaPanel = new CaptchaPanel(verifier);

// Montarlo dentro del JPanel placeholder del diseñador:
pnlCaptcha.setLayout(new java.awt.BorderLayout());
pnlCaptcha.removeAll();
pnlCaptcha.add(captchaPanel, java.awt.BorderLayout.CENTER);
pnlCaptcha.revalidate();
pnlCaptcha.repaint();

    }

    private javax.swing.ImageIcon loadScaledIcon(String resource, int maxW, int maxH) {
        java.net.URL url = getClass().getResource(resource);
        if (url == null) {
            return null;
        }
        java.awt.Image img = new javax.swing.ImageIcon(url).getImage();
        int w = img.getWidth(null), h = img.getHeight(null);
        if (w <= 0 || h <= 0) {
            return new javax.swing.ImageIcon(url);
        }
        double s = Math.min((double) maxW / w, (double) maxH / h);
        int nw = Math.max(1, (int) Math.round(w * s));
        int nh = Math.max(1, (int) Math.round(h * s));
        java.awt.Image scaled = img.getScaledInstance(nw, nh, java.awt.Image.SCALE_SMOOTH);
        return new javax.swing.ImageIcon(scaled);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        White_font = new javax.swing.JPanel();
        lblTitulo = new javax.swing.JLabel();
        lblOlvidoSuCarnet = new javax.swing.JLabel();
        txtCorreoPersonal = new javax.swing.JTextField();
        lblOlvidoSuContrasena = new javax.swing.JLabel();
        txtCarnet = new javax.swing.JTextField();
        btnEnviar = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();
        lblIcono = new javax.swing.JLabel();
        pnlCaptcha = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("ProblemasCarnetContrasena");
        setBackground(new java.awt.Color(204, 204, 204));
        setResizable(false);

        White_font.setBorder(javax.swing.BorderFactory.createEmptyBorder(16, 16, 16, 16));

        lblTitulo.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        lblTitulo.setText("¿Problemas con el carnet o la contraseña?");

        lblOlvidoSuCarnet.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblOlvidoSuCarnet.setText("¿Olvidó su carnet o aún no lo tienes?");

        txtCorreoPersonal.setToolTipText("Digite su correo electrónico personal");
        txtCorreoPersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCorreoPersonalActionPerformed(evt);
            }
        });

        lblOlvidoSuContrasena.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        lblOlvidoSuContrasena.setText("¿Olvidó la contraseña?");

        txtCarnet.setToolTipText("Digite su carnet");
        txtCarnet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCarnetActionPerformed(evt);
            }
        });

        btnEnviar.setBackground(new java.awt.Color(0, 102, 255));
        btnEnviar.setFont(new java.awt.Font("Cambria", 1, 24)); // NOI18N
        btnEnviar.setForeground(new java.awt.Color(255, 255, 255));
        btnEnviar.setText("Enviar");
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });

        btnClose.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        btnClose.setText("×");
        btnClose.setBorderPainted(false);
        btnClose.setContentAreaFilled(false);
        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setFocusPainted(false);
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        lblIcono.setBackground(new java.awt.Color(204, 0, 0));
        lblIcono.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        lblIcono.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/Fia_Support_Icon.png"))); // NOI18N
        lblIcono.setToolTipText("");

        pnlCaptcha.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        pnlCaptcha.setPreferredSize(new java.awt.Dimension(320, 160));
        pnlCaptcha.setLayout(new java.awt.BorderLayout());

        javax.swing.GroupLayout White_fontLayout = new javax.swing.GroupLayout(White_font);
        White_font.setLayout(White_fontLayout);
        White_fontLayout.setHorizontalGroup(
            White_fontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, White_fontLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(White_fontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, White_fontLayout.createSequentialGroup()
                        .addComponent(lblIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClose))
                    .addComponent(lblTitulo))
                .addGap(7, 7, 7))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, White_fontLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnEnviar)
                .addGap(170, 170, 170))
            .addGroup(White_fontLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(White_fontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlCaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, 317, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(White_fontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblOlvidoSuContrasena, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblOlvidoSuCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCorreoPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        White_fontLayout.setVerticalGroup(
            White_fontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(White_fontLayout.createSequentialGroup()
                .addGroup(White_fontLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(White_fontLayout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(btnClose))
                    .addComponent(lblIcono, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblTitulo)
                .addGap(41, 41, 41)
                .addComponent(lblOlvidoSuCarnet)
                .addGap(18, 18, 18)
                .addComponent(txtCorreoPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblOlvidoSuContrasena)
                .addGap(18, 18, 18)
                .addComponent(txtCarnet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pnlCaptcha, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEnviar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(White_font, javax.swing.GroupLayout.PREFERRED_SIZE, 464, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(White_font, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("Problemas con el Carnet o la Contrasena");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        String email = getSafeText(txtCorreoPersonal);
        String carnet = getSafeText(txtCarnet);

        if (email.isEmpty() && carnet.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this,
                    "Ingrese al menos su correo o su carnet.",
                    "Faltan datos", javax.swing.JOptionPane.WARNING_MESSAGE);
            return;
        }
        // Validar CAPTCHA antes de continuar
if (!captchaPanel.verifyNow()) {
    javax.swing.JOptionPane.showMessageDialog(this,
            "CAPTCHA incorrecto o expirado.\nInténtalo de nuevo.",
            "Validación", javax.swing.JOptionPane.WARNING_MESSAGE);
    return;
}


        javax.swing.JOptionPane.showMessageDialog(this,
                "Solicitud enviada. Revise su correo.",
                "Listo", javax.swing.JOptionPane.PLAIN_MESSAGE);

        dispose();
    }//GEN-LAST:event_btnEnviarActionPerformed

    private void txtCarnetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCarnetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCarnetActionPerformed

    private void txtCorreoPersonalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCorreoPersonalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCorreoPersonalActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                ProblemasCarnetContrasenaDialog dialog = new ProblemasCarnetContrasenaDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // --- Helpers de placeholder ---
    private void addPlaceholder(final javax.swing.JTextField field, final String hint) {
        final java.awt.Color fgNormal = field.getForeground();
        final java.awt.Color fgHint = java.awt.Color.GRAY;

        field.putClientProperty("isHint", true);
        field.setForeground(fgHint);
        field.setText(hint);

        field.addFocusListener(new java.awt.event.FocusAdapter() {
            @Override
            public void focusGained(java.awt.event.FocusEvent e) {
                if (Boolean.TRUE.equals(field.getClientProperty("isHint"))) {
                    field.setText("");
                    field.setForeground(fgNormal);
                    field.putClientProperty("isHint", false);
                }
            }

            @Override
            public void focusLost(java.awt.event.FocusEvent e) {
                if (field.getText().trim().isEmpty()) {
                    field.setForeground(fgHint);
                    field.setText(hint);
                    field.putClientProperty("isHint", true);
                }
            }
        });
    }

    private String getSafeText(javax.swing.JTextField field) {
        boolean isHint = Boolean.TRUE.equals(field.getClientProperty("isHint"));
        String txt = field.getText().trim();
        return isHint ? "" : txt;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel White_font;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JLabel lblIcono;
    private javax.swing.JLabel lblOlvidoSuCarnet;
    private javax.swing.JLabel lblOlvidoSuContrasena;
    private javax.swing.JLabel lblTitulo;
    private javax.swing.JPanel pnlCaptcha;
    private javax.swing.JTextField txtCarnet;
    private javax.swing.JTextField txtCorreoPersonal;
    // End of variables declaration//GEN-END:variables
}
